name: Upload site to Filecoin

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  upload:
    # Skip for forked PRs since secrets are unavailable there
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install deps
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Upload to Filecoin
        uses: ./.github/actions/filecoin-pin-upload-action
        with:
          privateKey: ${{ secrets.FILECOIN_WALLET_KEY }}
          path: dist
          minDays: 30
          maxTopUp: "5"     # USDFC
